import type { Metadata } from "next";
import "@repo/tailwind-config";
import "@repo/ui/styles.css";
import { FirebaseAuthProvider } from "context/auth/FirebaseAuthProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <FirebaseAuthProvider>
          {children}
        </FirebaseAuthProvider>
      </body>
    </html>
  );
}
